apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-data
  labels:
    type: local
    app: elasticsearch
    component: data
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/pv/elasticsearch-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master
  labels:
    type: local
    app: elasticsearch
    component: master
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/pv/elasticsearch-master"