apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
  labels:
    type: local
    app: prometheus
    component: alertmanager
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/pv/alertmanager"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server
  labels:
    type: local
    app: prometheus
    component: server
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/pv/prometheus-server"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  labels:
    type: local
    app: grafana
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/pv/grafana"